import { defineConfig, presetIcons } from "unocss";
import presetUno from "@unocss/preset-uno";
import presetAttributify from "@unocss/preset-attributify";
import presetTypography from "@unocss/preset-typography";
import transformerDirectives from "@unocss/transformer-directives";
import transformerVariantGroup from "@unocss/transformer-variant-group";

export default defineConfig({
    presets: [
        presetUno({
            dark: "class",
        }),
        presetAttributify(),
        presetTypography(),
        presetIcons(),
    ],
    transformers: [transformerDirectives(), transformerVariantGroup()],
    variants: [],
    shortcuts: {
        "text-base": "text-dark dark:text-white",
    },
    theme: {
        colors: {
            red: {
                1: "var(--color-red-1)",
                2: "var(--color-red-2)",
                3: "var(--color-red-3)",
                4: "var(--color-red-4)",
                5: "var(--color-red-5)",
                6: "var(--color-red-6)",
                7: "var(--color-red-7)",
                8: "var(--color-red-8)",
                9: "var(--color-red-9)",
            },
            pink: {
                1: "var(--color-pink-1)",
                2: "var(--color-pink-2)",
                3: "var(--color-pink-3)",
                4: "var(--color-pink-4)",
                5: "var(--color-pink-5)",
                6: "var(--color-pink-6)",
                7: "var(--color-pink-7)",
                8: "var(--color-pink-8)",
                9: "var(--color-pink-9)",
            },
            grape: {
                1: "var(--color-grape-1)",
                2: "var(--color-grape-2)",
                3: "var(--color-grape-3)",
                4: "var(--color-grape-4)",
                5: "var(--color-grape-5)",
                6: "var(--color-grape-6)",
                7: "var(--color-grape-7)",
                8: "var(--color-grape-8)",
                9: "var(--color-grape-9)",
            },
            violet: {
                1: "var(--color-violet-1)",
                2: "var(--color-violet-2)",
                3: "var(--color-violet-3)",
                4: "var(--color-violet-4)",
                5: "var(--color-violet-5)",
                6: "var(--color-violet-6)",
                7: "var(--color-violet-7)",
                8: "var(--color-violet-8)",
                9: "var(--color-violet-9)",
            },
            indigo: {
                1: "var(--color-indigo-1)",
                2: "var(--color-indigo-2)",
                3: "var(--color-indigo-3)",
                4: "var(--color-indigo-4)",
                5: "var(--color-indigo-5)",
                6: "var(--color-indigo-6)",
                7: "var(--color-indigo-7)",
                8: "var(--color-indigo-8)",
                9: "var(--color-indigo-9)",
            },
            blue: {
                1: "var(--color-blue-1)",
                2: "var(--color-blue-2)",
                3: "var(--color-blue-3)",
                4: "var(--color-blue-4)",
                5: "var(--color-blue-5)",
                6: "var(--color-blue-6)",
                7: "var(--color-blue-7)",
                8: "var(--color-blue-8)",
                9: "var(--color-blue-9)",
            },
            cyan: {
                1: "var(--color-cyan-1)",
                2: "var(--color-cyan-2)",
                3: "var(--color-cyan-3)",
                4: "var(--color-cyan-4)",
                5: "var(--color-cyan-5)",
                6: "var(--color-cyan-6)",
                7: "var(--color-cyan-7)",
                8: "var(--color-cyan-8)",
                9: "var(--color-cyan-9)",
            },
            teal: {
                1: "var(--color-teal-1)",
                2: "var(--color-teal-2)",
                3: "var(--color-teal-3)",
                4: "var(--color-teal-4)",
                5: "var(--color-teal-5)",
                6: "var(--color-teal-6)",
                7: "var(--color-teal-7)",
                8: "var(--color-teal-8)",
                9: "var(--color-teal-9)",
            },
            green: {
                1: "var(--color-green-1)",
                2: "var(--color-green-2)",
                3: "var(--color-green-3)",
                4: "var(--color-green-4)",
                5: "var(--color-green-5)",
                6: "var(--color-green-6)",
                7: "var(--color-green-7)",
                8: "var(--color-green-8)",
                9: "var(--color-green-9)",
            },
            lime: {
                1: "var(--color-lime-1)",
                2: "var(--color-lime-2)",
                3: "var(--color-lime-3)",
                4: "var(--color-lime-4)",
                5: "var(--color-lime-5)",
                6: "var(--color-lime-6)",
                7: "var(--color-lime-7)",
                8: "var(--color-lime-8)",
                9: "var(--color-lime-9)",
            },
            yellow: {
                1: "var(--color-yellow-1)",
                2: "var(--color-yellow-2)",
                3: "var(--color-yellow-3)",
                4: "var(--color-yellow-4)",
                5: "var(--color-yellow-5)",
                6: "var(--color-yellow-6)",
                7: "var(--color-yellow-7)",
                8: "var(--color-yellow-8)",
                9: "var(--color-yellow-9)",
            },
            orange: {
                1: "var(--color-orange-1)",
                2: "var(--color-orange-2)",
                3: "var(--color-orange-3)",
                4: "var(--color-orange-4)",
                5: "var(--color-orange-5)",
                6: "var(--color-orange-6)",
                7: "var(--color-orange-7)",
                8: "var(--color-orange-8)",
                9: "var(--color-orange-9)",
            },
            primary: {
                1: "var(--color-primary-1)",
                2: "var(--color-primary-2)",
                3: "var(--color-primary-3)",
                4: "var(--color-primary-4)",
                5: "var(--color-primary-5)",
                6: "var(--color-primary-6)",
                7: "var(--color-primary-7)",
                8: "var(--color-primary-8)",
                9: "var(--color-primary-9)",
            },
            secondary: {
                1: "var(--color-secondary-1)",
                2: "var(--color-secondary-2)",
                3: "var(--color-secondary-3)",
                4: "var(--color-secondary-4)",
                5: "var(--color-secondary-5)",
                6: "var(--color-secondary-6)",
                7: "var(--color-secondary-7)",
                8: "var(--color-secondary-8)",
                9: "var(--color-secondary-9)",
            },
            info: {
                1: "var(--color-info-1)",
                2: "var(--color-info-2)",
                3: "var(--color-info-3)",
                4: "var(--color-info-4)",
                5: "var(--color-info-5)",
                6: "var(--color-info-6)",
                7: "var(--color-info-7)",
                8: "var(--color-info-8)",
                9: "var(--color-info-9)",
            },
            success: {
                1: "var(--color-success-1)",
                2: "var(--color-success-2)",
                3: "var(--color-success-3)",
                4: "var(--color-success-4)",
                5: "var(--color-success-5)",
                6: "var(--color-success-6)",
                7: "var(--color-success-7)",
                8: "var(--color-success-8)",
                9: "var(--color-success-9)",
            },
            warning: {
                1: "var(--color-warning-1)",
                2: "var(--color-warning-2)",
                3: "var(--color-warning-3)",
                4: "var(--color-warning-4)",
                5: "var(--color-warning-5)",
                6: "var(--color-warning-6)",
                7: "var(--color-warning-7)",
                8: "var(--color-warning-8)",
                9: "var(--color-warning-9)",
            },
            error: {
                1: "var(--color-error-1)",
                2: "var(--color-error-2)",
                3: "var(--color-error-3)",
                4: "var(--color-error-4)",
                5: "var(--color-error-5)",
                6: "var(--color-error-6)",
                7: "var(--color-error-7)",
                8: "var(--color-error-8)",
                9: "var(--color-error-9)",
            },
        },
    },
});
